version: '3'
services:
  rabbitmq:
    hostname: rabbitmq
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - "rabbitmqdata:/var/lib/rabbitmq/mnesia"
volumes:
  rabbitmqdata: null

