server:
  port: ${port:0}
spring:
  profiles:
    active: usage_message

logging:
  level:
    org: ERROR

tutorial:
  client:
    duration: 10000

bln:
  simplesqueues:
    enabled: true
  simplesqueuescomack:
    enabled: false
  exchangesfanout:
    enabled: false
  exchangesdirect:
    enabled: false
  exchangestopic:
    enabled: false